services:
  server:
    image: server 
    container_name: server 
    build:
      context: ../backend
      dockerfile: ../docker/api.dockerfile
    ports:
      - 12345:12345
    volumes:
      - ../../envs/be.env:/app/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12345/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

volumes:
  data: