services:
  ui:
    build:
      context: ../
      dockerfile: docker/ui.dockerfile
    image: zunilab/sun-id-ui
    container_name: sun-id-ui
    ports:
      - 3000:3000
    volumes:
      - ../../envs/fe.env:/app/.env
      - ./ui.docker-entrypoint.sh:/app/docker-entrypoint.sh
    restart: always
