services:
  server:
    image: server 
    container_name: server 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 12345:12345
    volumes:
      - ./.env:/app/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12345/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

volumes:
  data: