on:
  push:
    branches:
      - staging 
    paths:
      - 'ui/**'
      - '.github/workflows/deploy-ui.yml'   

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}
  BASE_APP_DIR: /root/zuni/ui 

name: Build on Staging 

jobs:
  build:
    name: Build Staging
    runs-on: ubuntu-latest
    outputs:
      APP_IMAGE: ${{ steps.set_repo_name.outputs.APP_IMAGE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-release
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/ui.dockerfile 
          tags: ${{ steps.set_repo_name.outputs.APP_IMAGE }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
  